version: 2
updates:
  # manage dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: "numpy"
    - dependency-name: "pillow"
    - dependency-name: "bottle"
    - dependency-name: "apscheduler"
    - dependency-name: "tzlocal"
  # GH actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
