[tool.poetry]
name = "LED-Matrix"
version = "0.0.0"
description = "APA102 based LED-Matrix controlled by Raspberry Pi on Alpine Linux written in Python."
readme = "README.md"
license = "GPL-3.0-only"
authors = ["Marc Ammon <marc.ammon@hotmail.de>"]
homepage = "https://github.com/mammo0/LED-Matrix"


[tool.poetry.dependencies]
python = ">=3.11,<4.0"
spidev = "^3.6"
numpy = "^1.25.2"
pillow = "^10.1.0"
bottle = "^0.12.19"
imageio = "^2.31.5"
freetype-py = {git = "https://github.com/mammo0/freetype-py.git", branch = "led-matrix"}
simple-plugin-loader = "^3.0.0"
apscheduler = "^3.10.4"
astral = "^3.2"
tzlocal = "^5.2"

[tool.poetry.group.dev.dependencies]
pygame = "^2.5.2"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
metadata = false

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
