name: Dependabot Automerge
on:
  workflow_run:
    workflows: ["LED-Matrix Venv"]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
        github.event.workflow_run.conclusion == 'success' &&
        github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.pulls.merge({
              owner: context.actor,
              repo: context.payload.repository.name,
              pull_number: context.payload.workflow_run.pull_requests[0].number
            })
